apiVersion: apps/v1
kind: Deployment
metadata:
   name: user-service-dep
spec:
   selector:
      matchLabels:
         app: user-service-pod
   replicas: 1
   template:
      metadata:
         labels:
            app: user-service-pod
      spec:
         containers:
            - name: user-service-cont
              image: shahnawaz786/user-service:1.0
              imagePullPolicy: IfNotPresent
              ports:
                 - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
   name: user-service-svc
spec:
   selector:
      app: user-service-pod
   ports:
      - protocol: "TCP"
        port: 8081
        targetPort: 8081
   type: NodePort         